- bitbot/links.go
> Fix Spelling Error

- Dockerfile
- Gopkg.lock
- Gopkg.toml
- vendor/github.com/whyrusleeping/hellabot/hellabot.go
- vendor/gopkg.in/sorcix/irc.v1/.travis.yml
- vendor/gopkg.in/sorcix/irc.v1/LICENSE
- vendor/gopkg.in/sorcix/irc.v1/README.md
- vendor/gopkg.in/sorcix/irc.v1/constants.go
- vendor/gopkg.in/sorcix/irc.v1/doc.go
- vendor/gopkg.in/sorcix/irc.v1/internal/strings.go
- vendor/gopkg.in/sorcix/irc.v1/internal/strings_legacy.go
- vendor/gopkg.in/sorcix/irc.v1/message.go
- vendor/gopkg.in/sorcix/irc.v1/stream.go
because IRC is properly vendored now. Will send another patch when PR on upstream is accepted.
> Remove the go get ./.. from Dockerfile 

- .circleci/config.yml
Tests still don't pass, but this isn't a CircleCI problem anymore.
> Fixing circle ci tests

- cmd/root.go
> Add BeefyTrigger to default trigger map

- .gitignore
- CHANGELOG.md
- bitbot/bot.go
- bitbot/nick.go
- bitbot/triggerConditions_test.go
- bitbot/util.go
add an underscore to the nick if it is already taken
> Auto rename

- CHANGELOG.md
- bitbot/8ball.go
- cmd/root.go
> Add magic 8 ball

- bitbot/triggerConditions_test.go
> Add 8ball to trigger condition tests

- bitbot/bot.go
- bitbot/channelPopGauge.go
> Add new trigger to watch for RPL_LIST messages from server. Fixes #76

- bitbot/bot.go
- bitbot/db.go
- bitbot/markov.go
- bitbot/tarot.go
- bitbot/triggerConditions_test.go
- cmd/root.go
- go.mod
- go.sum
> Add markov trigger

- cmd/root.go
Added `markovInit` to the plugin map
> Updated `cmd/root.go` to include `markovInit`

- CHANGELOG.md
- bitbot/trollLauncher.go
- cmd/root.go
Has a chance to misfire, or on successful firing fires a random amount of trolls at the specified user, for a random amount of damage (d20). Bonus fluff: added random damage types from vanilla DnD for different kinds of trolls.
> Wrote `!troll` Troll Launcher (#45)

- bitbot/markov.go
- bitbot/trollLauncher.go
Removed snwcrsh source to cut down on training data
> Removed Snwcrsh Source

- CHANGELOG.md
- bitbot/markov.go
> reduce markov chance

- bitbot/tarot.go
> PM tarot reading when > 5 cards

- bitbot/login.go
> Update nickserv login to include bot nick

- cmd/root.go
- go.mod
we were incorrectly looking for `nickServPassword`
> Fix improperly bound nickserv config variable

- bitbot/info.go
- bitbot/version.go
- docker-build.sh
> Properly set version/commit/branch info at build time

- bitbot/channels.go
- bitbot/util.go
- go.mod
- go.sum
> Use new Part method in hbot.Bot

- bitbot/markov.go
- go.mod
I simply updated the help string of markovResponse, as I have no idea why the bot crashed the other day, and it doesn't seem to come from an empty markov chain.
> Updated markov help

- CHANGELOG.md
- bitbot/epeen.go
- cmd/root.go
> created epeen trigger

- CHANGELOG.md
> Update changelog with new release notes

- bitbot/epeen.go
> suser and m242 resume their epeen contest

- bitbot/epeen.go
- bitbot/ipinfo.go
- cmd/root.go
let me know when and where the tor socks5 is and ill rewrite this and point it there.
> Ipinfo add

- bitbot/ipinfo.go
- bitbot/util.go
- go.mod
added a contains functions function too
> Improve ACL checks

- bitbot/epeen.go
> undid m242s shinnanigans

- .github/workflows/pr_review.yml
- .github/workflows/test.yml
> Add test action

- README.md
Signed-off-by: Olivier Moreau m242 <m242@protonmail.com>
> Updated README.md, closes #147

- bitbot/ipinfo.go
Because the github workflow that I am trying to fix is on run on pr_review, I have to create a new PR.
> Fix golangci lint errors

- bitbot/covid19.go
Instead of looking for an "NAN" field which may or may not be there
(are you sorry, Canada?) we should run a collector value that adds the
totals for each province in a given country code.
> Get total for country by summing all provinces

- bitbot/covid19.go
Signed-off-by: Olivier Moreau m242 <m242@protonmail.com>
> Fixed total trigger addition loops

- bitbot/urbandict.go
- cmd/root.go
Signed-off-by: Olivier Moreau m242 <m242@protonmail.com>
> Added urbd trigger, closes #14

- bitbot/urbandict.go
Signed-off-by: Olivier Moreau m242 <m242@protonmail.com>
> Fixed improper definition sanitizing

- bitbot/channels.go
- bitbot/covid19.go
Allows to have province specific infos with "!covid [COUNTRYCODE] [Province Name]"
> Covid province
